Merging latest templates

diff --git a/my-overcloud/deployment/neutron/kill-script b/my-overcloud/deployment/neutron/kill-script
--- a/my-overcloud/deployment/neutron/kill-script
+++ b/my-overcloud/deployment/neutron/kill-script
@@ -17,27 +17,17 @@ SIG=$1
 PID=$2
 NETNS=$(ip netns identify ${PID})
 
-{% if container_cli == 'podman' %}
 if [ "x${NETNS}" == "x" ]; then
   CLI="nsenter --all --preserve-credentials -t 1 podman"
   SIG=9
 else
   CLI="nsenter --net=/run/netns/${NETNS} --preserve-credentials -m -t 1 podman"
 fi
-{% elif container_cli == 'docker' %}
-{% if docker_additional_sockets and docker_additional_sockets|length > 0-%}
-export DOCKER_HOST=unix://{{ docker_additional_sockets[0] }}
-{% endif -%}
-CLI='docker'
-{% else %}
-CLI='echo noop'
-{% endif %}
 
 kill_container() {
   add_date "Stopping container $1 ($2)"
   $CLI stop $2
-  add_date "Deleting container $1 ($2)"
-  $CLI rm $2
+  delete_container $1 $2
 }
 
 signal_container() {
@@ -49,10 +39,16 @@ signal_container() {
   $CLI kill --signal $SIGNAL $2
 }
 
+delete_container() {
+  add_date "Deleting container $1 ($2)"
+  $CLI rm $2 || echo "Deleting container $1 ($2) failed"
+}
+
+
 {% raw -%}
 if [ -f /proc/$PID/cgroup ]; then
   # Get container ID based on process cgroups
-  CT_ID=$(awk 'BEGIN {FS="[-.]"} /name=/{print $3}' /proc/$PID/cgroup)
+  CT_ID=$(awk 'BEGIN {FS=".scope|-"} /0::|:pids:/ {if ($(NF-1)) print $(NF-1);exit}' /proc/$PID/cgroup)
   CT_NAME=$($CLI inspect -f '{{.Name}}' $CT_ID)
 
   case $SIG in
@@ -64,6 +60,7 @@ if [ -f /proc/$PID/cgroup ]; then
       ;;
     15)
       signal_container $CT_NAME $CT_ID 15
+      delete_container $CT_NAME $CT_ID
       ;;
     *)
       add_date "Unknown action ${SIG} for ${CT_NAME} ${CT_ID}"
